# Generated by Django 3.2.12 on 2022-06-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('minute', models.IntegerField()),
                ('description', models.TextField()),
                ('active', models.BooleanField(verbose_name='Включен ли спам?')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
